name: satyam pipe line
on:
  workflow_dispatch: 
jobs:
  my_job:
  name: run to ubnatu
  runs-on: ubuntu-latest
  steps:
  - name: linux
    run: |
         whoami
         pwd
         ls
         echo "hello good morning"
  
